<a href="https://colab.research.google.com/github/mosta82/MLOps_learn/blob/main/mlops_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 10
b = 3
print("Sum:", a + b)
print("Multiply:", a * b)
print("Divide:", a / b)


Sum: 13
Multiply: 30
Divide: 3.3333333333333335


In [ ]:
numbers = [2, 5, 8, 1]
print("First element:", numbers[0])
numbers.append(10)
print("After appending:", numbers)
for num in numbers:
    print(num)


First element: 2
After appending: [2, 5, 8, 1, 10]
2
5
8
1
10


In [ ]:
student = {'name': 'Alice', 'age': 21}
print(student['name'])
student['grade'] = 'A'
print(student)



Alice
{'name': 'Alice', 'age': 21, 'grade': 'A'}


In [ ]:
def square(x):
    return x * x

result = square(5)
print(result)



25


In [ ]:
with open('sample.txt', 'w') as f:
    f.write('Hello World!\nThis is a test file.')

with open('sample.txt', 'r') as f:
    data = f.read()
    print(data)


Hello World!
This is a test file.


In [ ]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3, 4])
print(arr.mean())

df = pd.DataFrame({'name': ['Tom', 'Jerry'], 'age': [23, 21]})
print(df)


2.5
    name  age
0    Tom   23
1  Jerry   21


In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
print(df.head())


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [ ]:
# 1. Number of passengers
print("Total passengers:", len(df))

# 2. Columns in the dataset
print("Columns:", df.columns.tolist())

# 3. Number of survivors
print("Survived:", df['Survived'].sum())

# 4. Average age
print("Average age:", df['Age'].mean())

# 5. Gender distribution
print("Gender counts:\n", df['Sex'].value_counts())


Total passengers: 891
Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
Survived: 342
Average age: 29.69911764705882
Gender counts:
 Sex
male      577
female    314
Name: count, dtype: int64


In [ ]:
df.describe().to_csv("titanic_summary.csv")


In [ ]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4])
print("Array:", arr)

# Basic operations
print("Mean:", arr.mean())
print("Sum:", arr.sum())
print("Squared:", arr ** 2)

# 2D Arrays (matrices)
mat = np.array([[1, 2], [3, 4]])
print("Matrix:\n", mat)
print("Matrix Transpose:\n", mat.T)


Array: [1 2 3 4]
Mean: 2.5
Sum: 10
Squared: [ 1  4  9 16]
Matrix:
 [[1 2]
 [3 4]]
Matrix Transpose:
 [[1 3]
 [2 4]]


In [ ]:
import pandas as pd

# Create a DataFrame (table)
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [24, 19, 22]
})

print(df)

# Select a column
print("Ages:", df['age'])

# Filter rows
print("Older than 20:\n", df[df['age'] > 20])

# Add a new column
df['age_plus_5'] = df['age'] + 5
print(df)

# Describe (quick summary)
print(df.describe())


      name  age
0    Alice   24
1      Bob   19
2  Charlie   22
Ages: 0    24
1    19
2    22
Name: age, dtype: int64
Older than 20:
       name  age
0    Alice   24
2  Charlie   22
      name  age  age_plus_5
0    Alice   24          29
1      Bob   19          24
2  Charlie   22          27
             age  age_plus_5
count   3.000000    3.000000
mean   21.666667   26.666667
std     2.516611    2.516611
min    19.000000   24.000000
25%    20.500000   25.500000
50%    22.000000   27.000000
75%    23.000000   28.000000
max    24.000000   29.000000


In [ ]:
# Write a file
with open('myfile.txt', 'w') as f:
    f.write("Hello!\nPython is awesome.\n")

# Read the file
with open('myfile.txt', 'r') as f:
    data = f.read()
    print(data)


Hello!
Python is awesome.



In [ ]:
with open('myfile.txt', 'w') as f:
    f.write("This is my output!\n")

with open("myfile.txt", "r") as f:
    data = f.read()
    print(data)



This is my output!



In [ ]:
import pandas as pd

# Read CSV from local or web
# df = pd.read_csv('mydata.csv')      # Local file
# Replace the placeholder URL with the actual URL of your CSV file
# For example, you might want to reload the Titanic dataset
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

print(df.head())    # Show first 5 rows

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [ ]:
import numpy as np

arr = np.arange(1, 11)  # [1, 2, ..., 10]
print("Array:", arr)
print("Mean:", arr.mean())
print("Standard deviation:", arr.std())


Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Standard deviation: 2.8722813232690143


In [ ]:
import pandas as pd

# Sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'score': [55, 38, 72, 25]
}
df = pd.DataFrame(data)

# Add 'pass' column: True if score >= 40, else False
df['pass'] = df['score'] >= 40

print(df)


      name  score   pass
0    Alice     55   True
1      Bob     38  False
2  Charlie     72   True
3    David     25  False


In [ ]:
# Write to the file
with open('notes.txt', 'w') as f:
    f.write("Name: Abrar\n")
    f.write("Favorite language: Python\n")

# Read the file
with open('notes.txt', 'r') as f:
    content = f.read()
    print(content)


Name: Abrar
Favorite language: Python



In [ ]:
import pandas as pd

df = pd.DataFrame({
    'city': ['Dhaka', 'Chittagong', 'Sylhet'],
    'population_million': [21, 4, 1]
})
df.to_csv('cities.csv', index=False)

# Check that it worked
print(pd.read_csv('cities.csv'))


         city  population_million
0       Dhaka                  21
1  Chittagong                   4
2      Sylhet                   1


In [ ]:
class Car:
    def __init__(self, brand, year):
        self.brand = brand
        self.year = year

    def display(self):
        print(f"This car is a {self.brand}, made in {self.year}.")

# Create an object and use the method
my_car = Car('Toyota', 2018)
my_car.display()


This car is a Toyota, made in 2018.


In [ ]:
import numpy as np
import pandas as pd

# Create random numbers using numpy
scores = np.random.randint(30, 100, 5)
names = ['Tuhin', 'Anik', 'Nadia', 'Sumon', 'Mina']

df = pd.DataFrame({'name': names, 'score': scores})
df['pass'] = df['score'] >= 40
print(df)


    name  score   pass
0  Tuhin     87   True
1   Anik     31  False
2  Nadia     88   True
3  Sumon     66   True
4   Mina     48   True


In [1]:
import numpy as np

data = np.array([1, 2, 3, 4])
print(data.mean())  # Average
print(np.log(data))  # Log transform (used in ML)


2.5
[0.         0.69314718 1.09861229 1.38629436]


In [2]:
import pandas as pd

df = pd.DataFrame({
    'transaction_id': [101, 102, 103],
    'amount': [200, 150, 300],
    'is_fraud': [0, 1, 0]
})

print(df.head())           # View top rows
print(df['amount'].mean()) # Average amount
print(df[df['is_fraud'] == 1])  # Filter fraud rows


   transaction_id  amount  is_fraud
0             101     200         0
1             102     150         1
2             103     300         0
216.66666666666666
   transaction_id  amount  is_fraud
1             102     150         1


In [3]:
class ModelEvaluator:
    def __init__(self, name, accuracy):
        self.name = name
        self.accuracy = accuracy

    def evaluate(self):
        print(f"{self.name} achieved {self.accuracy * 100:.2f}% accuracy")

evaluator = ModelEvaluator("RandomForest", 0.93)
evaluator.evaluate()


RandomForest achieved 93.00% accuracy
